### ISSUE TITLE
Straight line drawing

### ISSUE THREAD

**Issue by MYasirSheikh** [qharley/Morgan#5]
As you know, it's a chunk of code from prepare_move function

Is this part of the code for straight line drawing (since the arm has a tendency of radial movement because of SCARA). If YES, can someone explain me the logic.. I badly need it for some development. help me pleaseeee..

float seconds = 6000 * cartesian_mm / feedrate / feedmultiply;
  int steps = max(1, int(DELTA_SEGMENTS_PER_SECOND * seconds));
  for (int s = 1; s <= steps; s++) {
    float fraction = float(s) / float(steps);
    for(int8_t i=0; i < NUM_AXIS; i++) {
      destination[i] = current_position[i] + difference[i] * fraction;
    }
    calculate_delta(destination);
    plan_buffer_line(delta[X_AXIS], delta[Y_AXIS], delta[Z_AXIS],
                     destination[E_AXIS], feedrate*feedmultiply/60/100.0,
                     active_extruder);
  }
  
   
  for(int8_t i=0; i < NUM_AXIS; i++) {
    current_position[i] = destination[i];
  }
}

**Comment by qharley** [comment]
It has been quite a while since I did any work on marlin... Mostly my fault since I did not know how to keep the software updated and how to do pull requests. 

I have since started working on Smoothieware, and it is a much better platform for axial robots like Morgan, especially because of the superior processing ability of the ARM chip.
